# run the testsuite on travis-ci.org
---
# run once for each of these
env:
  global:
  - enable_coverage=yes
  - PGVERSION=12

language: C
dist: bionic
sudo: required

before_install:
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls

install:
  # remove all existing postgresql
  - sudo rm -rf /etc/postgresql /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
  - sudo apt update
  - sudo pip install cpp-coveralls
  - sudo apt -y install postgresql-12 postgresql-client-12 postgresql-server-dev-12
  - sudo apt-get install -y postgresql-common
  - sudo apt-get install -y bison flex libicu-dev libssl-dev git
  - sudo -u postgres createuser --superuser $USER
  - sudo sed -i 's/#wal_level = replica/wal_level = logical/g' /etc/postgresql/12/main/postgresql.conf
  - sudo service postgresql@12-main restart
  - git clone https://github.com/idrawone/wal2mongo.git

script:
  - ./configure --enable-gcov && make && make check
  - cd wal2mongo
  - export PATH=/usr/lib/postgresql/12/bin:$PATH
  - USE_PGXS=1 make
  - sudo USE_PGXS=1 make install
  - USE_PGXS=1 make installcheck-force
  - if test -s regression.diffs; then cat regression.diffs; fi

after_success:
        #- sudo chmod 666 *.gcda
  - coveralls --exclude wal2mongo.c --gcov-options '\-lp'

deploy:
  provider: releases
  api_key: 
    secure: "oKkF1Dk6a0O7b3vdOUzKJh8onSF2q+FFVFZm7HOceVWfNmc2n8dU+7Y53XSY8AxMQiUOpXXDxDNHHRrVdKGNtu0RxwZ0JoHANKPrNWgi3AO4ENUTSkBpbPRyVV+TakMGvOfhccRU1Arg36ZMA0odISrA8a+xbRtif97OxsPaWU/AvlURm2bA7RYYCCsqv/tCESuPmJfguLd7LIEVxBV2DbEc9vRQFbwInGrsrjyOjPa+rKecrnzSuqVJ2uFsKxwCAY2qZKNrUqf9M8QSCx2URsBgBacG+bgZkBpb31xL/ccakHuJ3VAv5AZrLKsropSGr953Y7K7Sq5JVgYGRuYYh+4hHiHw9lM+jEQ1tO06SgChzYYO+EvSRSqU2YM0Yg5JVtQn+P2O4EgnR+Vp3AIz8iGfPVzJ6+MSFnCtUJL+H3KYRSj48Q9qxzLrB9yvNU3q/hWk5kso08ZFZIYOPS0G8DNIeHcyOVxGzAnnoQ2CqKfIEyWTu/htTHNi2AKhdRIKX/yVz0/+Fv9RkWm/mVFQe7k0dYvs6VfNpotilEMQVmV18mOttd/C++eziGIkx6dJU5KUJDo6gm3zl3UnPYgOYXP4EeDSGyNBdVjHe7E4k2lyp+r/l8kYYCWoSyKOCN6vvCt4VSTqPI5vfgZbXygRL42wcxNspQbZJXl5RO7EuE4="
  file_glob: true
  file: "*.so"
  skip_cleanup: true
  on:
    repo: idrawone/wal2mongo
    branch: release
    tags: true
