# run the testsuite on travis-ci.org
---
# run once for each of these
env:
  - PGVERSION=12

language: C
dist: bionic
sudo: required

before_install:
  - sudo apt-get update -qq

install:
  # remove all existing postgresql
  - sudo rm -rf /etc/postgresql /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
  - sudo apt update
  - sudo apt -y install postgresql-12 postgresql-client-12 postgresql-server-dev-12
  - sudo apt-get install -y postgresql-common
  - sudo apt-get install -y bison flex libicu-dev libssl-dev git
  - sudo -u postgres createuser --superuser $USER
  - sudo sed -i 's/#wal_level = replica/wal_level = logical/g' /etc/postgresql/12/main/postgresql.conf
  - sudo service postgresql@12-main restart
  - git clone https://github.com/idrawone/wal2mongo.git

script:
  - cd wal2mongo
  - export PATH=/usr/lib/postgresql/12/bin:$PATH
  - USE_PGXS=1 make
  - sudo USE_PGXS=1 make install
  - USE_PGXS=1 make installcheck-force
  - if test -s regression.diffs; then cat regression.diffs; fi

deploy:
  provider: releases
  api_key: 
    secure: "kSf9oJCzp3+7JNtZZX8wLygOMSxhKNM9uwBhb6Ufb5HbvsimX3pkwrKTnKHX6d9BYmHPujPZwLeWqu9/VNZBQThdu3R6GAjVptb5Z/fpwL4Ew28ClI1860pzbDchN7kBx6qqGE+DJOQO4h+FO+ug1RdKl6iLT2/8voVn1J+D1welym4/oyJ+n0kt6XOwZNb6eeCeixOrLeKrvyG2ndRaIjA3qoyccVh2wu9krI6lVCTp4Rze265jwIrp5ezzAlI0+GZLNk+YKXNSZC2kxx4NFy5jLl9j6nU43MwznLupr6ywCBgd+5tty+CvYhj/9IgcvvG4tqTzCWkVssut9fhgQLlPnN7wI5X27/LXx46O0RrX9isYXkcSBnCT15ai4/GAeggHDbqnHHPlmjp9ETjZ1D6JI34gxwq37/IAiWUmY6NXzlImnggE+vlDuA3m4gCxCjuHXc8ADiUBjmggeLUN4VyLy+uiHo9IBMa9kjTuuRuyOnA1erP6vyMHjy6hMKyaUwM+K0TRNHtmKLZchHj8k7Oo5uxssfN8a3ecMXTKRknJoADTNXki5iaPG9/CblV09KduXNyNJbFmJycRNa24115jlu3F8cPR8Kz7b24XyFrUTwxMqWBaQyQUashaB34Pe+qluPyt0ODfB0pRHVKPHyiYG8hIc+mrQC+Rho6gUZc="
  file_glob: true
  file: "*.so"
  skip_cleanup: true
  on:
    branch: release
