# run the testsuite on travis-ci.org
---
# run once for each of these
env:
  global:
  - PGVERSION=12

language: C
dist: bionic
sudo: required

before_install:
  - sudo apt-get update -qq

install:
  # remove all existing postgresql
  - sudo rm -rf /etc/postgresql /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
  - sudo apt update
  - sudo apt -y install postgresql-12 postgresql-client-12 postgresql-server-dev-12
  - sudo apt-get install -y postgresql-common
  - sudo apt-get install -y bison flex libicu-dev libssl-dev git
  - sudo -u postgres createuser --superuser $USER
  - sudo sed -i 's/#wal_level = replica/wal_level = logical/g' /etc/postgresql/12/main/postgresql.conf
  - sudo service postgresql@12-main restart
  - git clone https://github.com/idrawone/wal2mongo.git

script:
  - cd wal2mongo
  - export PATH=/usr/lib/postgresql/12/bin:$PATH
  - USE_PGXS=1 make
  - sudo USE_PGXS=1 make install
  - USE_PGXS=1 make installcheck-force
  - if test -s regression.diffs; then cat regression.diffs; fi

    #deploy:
    #  provider: releases
    #  api_key: 
    #    secure: GaRvrxsNhrzKcnwzZikysYZoNSGFBzp0GCvzI/C5MBJ78cDKF5bS9MXg+6mKIerGntrzT5pCla4WCrQaJ980+WM3D8v7/fTkuChvKW/4QEIE+4T5EtDtzjvq8//cNYj84JHei7mNbKxQm9Z9BEd+y4TIPyQ2aceuwl9MSmMb03njAuJuRp6SqK7T/8XZ1/nLOKMRhR1DYHrxOiYj33b7/9M5Hshn0RchRDZzz/AiwDXX8DGpB1ru9Arsm4opzPjYz7n+jH1/TgPg9UoQTCd753ye8x0YG49fmUC4PI/U32lHL5fv/VgRKz038luPZzSkIrDfLx2z4cCSZ/Vk0CSRHvqfFfdILR+4nYO8jH2Y5SX167byV8yxYbmuZgKOfubfy31uivCfJKL+LtvAs18jvFdSqJeKogIadsXECuoztA2DZB/9ncUasSNhnbRyShF37JfvmvO2tcMF5TXE14afGmbD/VEXQ2eBIu9KDP3LNQ0bZEZj9EZoBR683ht/dvjV1UBdG5Etmy+CkcYQXFV8O2WyLOCUPzDLOG6/HCaW3Q5GRnl5z8w6hGbOwRsroV3fxPtx46LpyTiRbYxy1Xfbh3cYixKtb0mgzIih+5j0bLy/UxtW0g3lOcK7PZPV7E+4mez5ecNm5OCw4z63HRs0ZMhDNgwdKZGTLkJ/t84MMow=
    #  file_glob: true
    #  file: "*.so"
    #  skip_cleanup: true
    #  on:
    #    branch: release
