# run the testsuite on travis-ci.org
---
# run once for each of these
env:
  - PGVERSION=12

language: C
dist: bionic
sudo: required

before_install:
  - sudo apt-get update -qq

install:
  # remove all existing postgresql
  - sudo rm -rf /etc/postgresql /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
  - sudo apt update
  - sudo apt -y install postgresql-12 postgresql-client-12 postgresql-server-dev-12
  - sudo apt-get install -y postgresql-common
  - sudo apt-get install -y bison flex libicu-dev libssl-dev git
  #- sudo -u postgres createuser --superuser $USER
  - git clone https://github.com/idrawone/wal2mongo.git

script:
  - cd wal2mongo
  - export PATH=/usr/lib/postgresql/12/bin:$PATH
  - USE_PGXS=1 make
  - sudo USE_PGXS=1 make install
  - USE_PGXS=1 make installcheck-force
  - if test -s regression.diffs; then cat regression.diffs; fi

